### ISSUE TITLE
Consider confinode

### ISSUE THREAD

**Issue by sveyret** [bmpieretti/splash-scripts#1]
I'd like to suggest you to use [confinode](https://www.npmjs.com/package/confinode) as I think it could be helpful to this project: already managing extends and indirections, controlling your configuration, etc.
Whether you use it or not, I'd really appreciate to know why, this would help me to improve my work. And if you have questions or want help on this, please ask!

**Comment by bmpieretti** [comment]
Hey @sveyret! I appreciate you taking the time to make me aware of your project, but I probably won't swap at the moment due to lack of [cosmicconfig](https://github.com/davidtheclark/cosmiconfig) support. I know your API roughly supports most of what it also does, but it's a tad more battle tested and has a pretty well known selection of config support.

I'll keep an eye on confinode though, as the extends support would have been great to have before building a bunch of it myself!
